### PR TITLE
Border Lines on the page

### PR DESCRIPTION
**Pull request by DasunSL**
need to change

### CODE REVIEW

**Comment by DasunSL** [comment]
How do you suppose to change the border lines on page

**Comment by rajivsri1996** [comment]
How do you suppose me to change ???

**Comment by DasunSL** [comment]
Thank you for the quick response...I will make some variations and let you to know...

**Comment by DasunSL** [comment]
bad finishing

According to this, see around the black border line.

**Comment by DasunSL** [comment]
And also the Area of the middle is keeping empty.

**Comment by rajivsri1996** [comment]
Yes of course I have seen several mistakes what i have done in here. what do you want to suggest me for that..?

**Pull request merged**
